// admin-next/app/sites/[siteId]/page.tsx
import Link from "next/link"
import { notFound } from "next/navigation"
import { HugeiconsIcon } from "@hugeicons/react"
import { ArrowLeft01Icon } from "@hugeicons/core-free-icons"

import { getSupabaseAdmin } from "@/lib/supabase-server"
import type { CmsContentRow, SiteAdminRow, SiteRow } from "@/lib/sites-types"

async function loadSite(
  siteId: string,
): Promise<
  | { ok: true; site: SiteRow; admins: SiteAdminRow[]; cmsContent: CmsContentRow[] }
  | { ok: false; status: 404 | 500; message: string }
> {
  try {
    const supabase = getSupabaseAdmin()

    const { data: siteRow, error: siteErr } = await supabase
      .from("sites")
      .select("id, slug, name, created_at")
      .eq("id", siteId)
      .maybeSingle()

    if (siteErr) return { ok: false, status: 500, message: siteErr.message }
    if (!siteRow) return { ok: false, status: 404, message: "Site not found" }

    const site = siteRow as SiteRow

    const { data: adminRows, error: adminsErr } = await supabase
      .from("cms_admins")
      .select("user_id, created_at")
      .eq("site_id", siteId)
      .order("created_at", { ascending: false })

    if (adminsErr) return { ok: false, status: 500, message: adminsErr.message }

    const admins: SiteAdminRow[] = await Promise.all(
      (adminRows ?? []).map(async (row) => {
        const { data, error } = await supabase.auth.admin.getUserById(row.user_id)
        if (error || !data?.user) {
          return { user_id: row.user_id, email: null, created_at: row.created_at }
        }
        return { user_id: row.user_id, email: data.user.email ?? null, created_at: row.created_at }
      }),
    )

    const { data: contentRows, error: contentErr } = await supabase
      .from("cms_content")
      .select("key, kind, value, updated_at, updated_by")
      .eq("site_id", siteId)
      .order("key", { ascending: true })

    if (contentErr) return { ok: false, status: 500, message: contentErr.message }

    return { ok: true, site, admins, cmsContent: (contentRows ?? []) as CmsContentRow[] }
  } catch (e) {
    return { ok: false, status: 500, message: e instanceof Error ? e.message : String(e) }
  }
}

export default async function SiteDetailPage({ params }: { params: Promise<{ siteId: string }> }) {
  const { siteId } = await params
  const result = await loadSite(siteId)

  if (!result.ok && result.status === 404) {
    notFound()
  }

  return (
    <div className="mx-auto max-w-3xl p-6">
      <Link
        href="/sites"
        className="text-muted-foreground hover:text-foreground mb-4 inline-flex items-center gap-1 text-[12px]"
      >
        <HugeiconsIcon icon={ArrowLeft01Icon} size={12} strokeWidth={1.75} />
        All sites
      </Link>

      {!result.ok ? (
        <div className="text-muted-foreground rounded-md border p-6 text-center text-[13px]">
          Couldn&apos;t load site. {result.message}
        </div>
      ) : (
        <>
          <header className="mb-6">
            <h1 className="text-[20px] font-semibold leading-tight">{result.site.name}</h1>
            <p className="text-muted-foreground mt-1 font-mono text-[12px]">
              /{result.site.slug} · {result.site.id}
            </p>
          </header>

          <section className="mb-8">
            <h2 className="text-muted-foreground mb-2 text-[11px] font-semibold uppercase tracking-wide">
              Admins
            </h2>
            {result.admins.length === 0 ? (
              <p className="text-muted-foreground text-[13px]">No admins assigned.</p>
            ) : (
              <ul className="divide-border divide-y rounded-md border">
                {result.admins.map((a) => (
                  <li key={a.user_id} className="flex items-center justify-between px-4 py-2.5">
                    <div className="min-w-0">
                      <div className="text-foreground text-[13px]">{a.email ?? "(no email)"}</div>
                      <div className="text-muted-foreground mt-0.5 truncate font-mono text-[11px]">
                        {a.user_id}
                      </div>
                    </div>
                    <span className="text-muted-foreground text-[11px]">
                      {new Date(a.created_at).toLocaleDateString()}
                    </span>
                  </li>
                ))}
              </ul>
            )}
            <p className="text-muted-foreground mt-2 text-[11px]">
              Adding admins / generating one-time login links is still in the legacy
              <code className="font-mono"> /admin</code> app for now.
            </p>
          </section>

          <section>
            <h2 className="text-muted-foreground mb-2 text-[11px] font-semibold uppercase tracking-wide">
              CMS content
            </h2>
            {result.cmsContent.length === 0 ? (
              <p className="text-muted-foreground text-[13px]">No CMS content stored.</p>
            ) : (
              <p className="text-muted-foreground text-[13px]">
                {result.cmsContent.length} entr{result.cmsContent.length === 1 ? "y" : "ies"} —
                edit in the legacy <code className="font-mono">/admin</code> app for now.
              </p>
            )}
          </section>
        </>
      )}
    </div>
  )
}

// mapsLeadsFetcher/admin/src/routes/sites/[siteId]/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import {
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle
	} from '$lib/components/ui/card/index.js';
	import * as Table from '$lib/components/ui/table/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import SiteAdminsDataTable from '$lib/components/site-admins-data-table.svelte';
	import type { CmsContentRow } from '$lib/sites.types';
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { ArrowLeft01Icon } from '@hugeicons/core-free-icons';

	let { data }: { data: PageData } = $props();

	function formatUpdated(iso: string): string {
		const d = new Date(iso);
		if (Number.isNaN(d.getTime())) return iso;
		return d.toLocaleString(undefined, {
			dateStyle: 'medium',
			timeStyle: 'short'
		});
	}

	function valuePreview(row: CmsContentRow): string {
		try {
			return JSON.stringify(row.value, null, 2);
		} catch {
			return String(row.value);
		}
	}
</script>

<div class="flex flex-1 flex-col gap-6 p-4">
	<header class="flex items-center gap-1">
		<Button
			href="/sites"
			variant="ghost"
			size="icon-sm"
			class="text-muted-foreground hover:text-foreground shrink-0"
			aria-label="Back to sites"
		>
			<HugeiconsIcon icon={ArrowLeft01Icon} data-icon="inline-start" strokeWidth={2} />
		</Button>
		<h1 class="text-xl leading-none font-semibold tracking-tight">{data.site.name}</h1>
	</header>

	<div class="grid gap-6 lg:grid-cols-2">
		<Card class="flex min-h-[280px] flex-col">
			<CardHeader>
				<CardTitle class="text-base">Admins</CardTitle>
			</CardHeader>
			<CardContent class="flex-1 pt-0">
				<SiteAdminsDataTable siteId={data.site.id} admins={data.admins} />
			</CardContent>
		</Card>

		<Card class="flex min-h-[200px] flex-col">
			<CardHeader class="pb-2">
				<CardTitle class="text-base">Events</CardTitle>
			</CardHeader>
			<CardContent class="flex flex-1 flex-col justify-center pt-0">
				<p class="text-muted-foreground text-center text-sm">No events yet.</p>
			</CardContent>
		</Card>
	</div>

	<Card>
		<CardHeader class="pb-2">
			<CardTitle>Content keys</CardTitle>
		</CardHeader>
		<CardContent>
			{#if data.cmsContent.length === 0}
				<p class="text-muted-foreground text-sm">No content keys yet.</p>
			{:else}
				<div class="border-border max-h-[min(70vh,720px)] overflow-auto rounded-md border">
					<Table.Root>
						<Table.Header>
							<Table.Row class="hover:bg-transparent">
								<Table.Head class="bg-card sticky top-0 z-[1] w-[22%] font-semibold">Key</Table.Head>
								<Table.Head class="bg-card sticky top-0 z-[1] w-[8%] font-semibold">Kind</Table.Head>
								<Table.Head class="bg-card sticky top-0 z-[1] font-semibold">Value</Table.Head>
								<Table.Head class="bg-card sticky top-0 z-[1] w-[14%] font-semibold">Updated</Table.Head>
								<Table.Head class="bg-card sticky top-0 z-[1] w-[18%] font-semibold">Updated by</Table.Head>
							</Table.Row>
						</Table.Header>
						<Table.Body>
							{#each data.cmsContent as row (row.key)}
								<Table.Row>
									<Table.Cell class="align-top font-mono text-xs break-all">{row.key}</Table.Cell>
									<Table.Cell class="align-top">
										<span class="bg-muted rounded-md px-1.5 py-0.5 text-xs font-medium">
											{row.kind}
										</span>
									</Table.Cell>
									<Table.Cell class="align-top">
										<pre
											class="text-muted-foreground max-h-40 overflow-auto font-mono text-xs whitespace-pre-wrap break-all"
										>{valuePreview(row)}</pre>
									</Table.Cell>
									<Table.Cell class="text-muted-foreground align-top text-xs whitespace-nowrap">
										{formatUpdated(row.updated_at)}
									</Table.Cell>
									<Table.Cell class="text-muted-foreground align-top font-mono text-xs break-all">
										{row.updated_by ?? '—'}
									</Table.Cell>
								</Table.Row>
							{/each}
						</Table.Body>
					</Table.Root>
				</div>
			{/if}
		</CardContent>
	</Card>
</div>
